//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida
    {
        public int Salida_ID { get; set; }
        public int Empleado { get; set; }
        public string Tipo_Salida { get; set; }
        public string Motivo { get; set; }
        public System.DateTime Fecha_Salida { get; set; }
    
        public virtual Empleado Empleado1 { get; set; }
    }
}
