//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_First.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registro
    {
        public int Id { get; set; }
        public string Nombre { get; set; }

        [Range(18,100)]
        public short Edad { get; set; }

        public string Carrera { get; set; }
        public short Cuatrimestre { get; set; }
    }
}
