//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sistemaNominaEntities : DbContext
    {
        public sistemaNominaEntities()
            : base("name=sistemaNominaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MantenimientoCargo> MantenimientoCargos { get; set; }
        public virtual DbSet<MantenimientoDepartamento> MantenimientoDepartamentos { get; set; }
        public virtual DbSet<MantenimientoEmpleado> MantenimientoEmpleados { get; set; }
        public virtual DbSet<Nomina> Nominas { get; set; }
        public virtual DbSet<SalidaEmpleado> SalidaEmpleados { get; set; }
        public virtual DbSet<VacacionesEmpleado> VacacionesEmpleados { get; set; }
    }
}
