//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int Id { get; set; }
        public string AñoNomina { get; set; }
        public string MesNomina { get; set; }
        public Nullable<int> MontoTotal { get; set; }
    }
}
