//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaITLA2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendum
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int Telefono { get; set; }
        public string Direccion { get; set; }
        public string Evento { get; set; }
        public string Lugar { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
