//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MantenimientoEmpleado()
        {
            this.SalidaEmpleados = new HashSet<SalidaEmpleado>();
            this.VacacionesEmpleados = new HashSet<VacacionesEmpleado>();
        }
    
        public int Id { get; set; }
        public string CodigoEmpleado { get; set; }
        public string NombreEmpleado { get; set; }
        public string ApellidoEmpleado { get; set; }
        public string TelefonoEmpleado { get; set; }
        public string DepartamentoEmpleado { get; set; }
        public string CargoEmpleado { get; set; }
        public Nullable<System.DateTime> FechaIngresoEmpleado { get; set; }
        public int SalarioEmpleado { get; set; }
        public string Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaEmpleado> SalidaEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacacionesEmpleado> VacacionesEmpleados { get; set; }
    }
}
