//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoDepartamento
    {
        public int Id { get; set; }
        public string CodigoDepartamento { get; set; }
        public string Nombre { get; set; }
        public string Encargado { get; set; }
    }
}
