//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacacionesEmpleado
    {
        public int Id { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public string CorrespondienteAño { get; set; }
        public string ComentarioVacacion { get; set; }
    
        public virtual MantenimientoEmpleado MantenimientoEmpleado { get; set; }
    }
}
